# Generated by Django 5.2.14 on 2026-05-25 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Номи категория')),
                ('icon', models.CharField(blank=True, help_text='Масалан: phone, car, home', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Номи маҳсулот')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нарх (сомонӣ)')),
                ('description', models.TextField(verbose_name='Тавсифи маҳсулот')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Сурат')),
                ('status', models.CharField(choices=[('new', 'Нав'), ('used', 'Кӯҳна (Б/У)')], default='new', max_length=10, verbose_name='Ҳолат')),
                ('location', models.CharField(choices=[('dushanbe', 'Душанбе'), ('khujand', 'Хуҷанд'), ('bokhtar', 'Бохтар'), ('kulob', 'Кӯлоб'), ('istravshan', 'Истаравшан'), ('konibodom', 'Конибодом'), ('panjakent', 'Панҷакент'), ('tursunzoda', 'Турсунзода'), ('hisor', 'Ҳисор'), ('vahdat', 'Ваҳдат'), ('rshn', 'Рӯдакӣ / Вахш / дигар ноҳияҳо')], default='dushanbe', max_length=30, verbose_name='Шаҳр/Ноҳия')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон барои алоқа')),
                ('delivery', models.BooleanField(default=False, verbose_name='Хизматрасонии расонидан (Доставка)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Вакти дақиқи эълон')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Соҳиби эълон')),
            ],
        ),
    ]
