# Generated by Django 5.2.14 on 2026-05-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_delivery',
            field=models.BooleanField(default=False, verbose_name='Имконияти расонидан'),
        ),
    ]
