# Generated by Django 5.2.14 on 2026-05-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_has_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
