# Generated by Django 5.2.14 on 2026-06-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vip_cheque',
            field=models.ImageField(blank=True, null=True, upload_to='vip_cheques/', verbose_name='Чеки пардохти VIP'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='Статуси VIP'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('dushanbe', 'ш. Душанбе'), ('khujand', 'ш. Хуҷанд'), ('bokhtar', 'ш. Бохтар'), ('kulob', 'ш. Кӯлоб'), ('vahdat', 'ш. Ваҳдат'), ('hissor', 'ш. Ҳисор'), ('tursunzoda', 'ш. Турсунзода'), ('roghun', 'ш. Роғун'), ('nurek', 'ш. Норак'), ('levakant', 'ш. Левакант'), ('khorugh', 'ш. Хоруғ'), ('temurmalik', 'н. Темурмалик'), ('dangara', 'н. Данғара'), ('vose', 'н. Восеъ'), ('yavon', 'н. Ёвон'), ('vakhsh', 'н. Вахш'), ('dusti', 'н. Дӯстӣ'), ('kushoniyon', 'н. Кӯшониён'), ('baljuvon', 'н. Балҷувон'), ('muminobod', 'н. Муъминобод'), ('panj', 'н. Панҷ'), ('farkhor', 'н. Фархор'), ('khovaling', 'н. Ховалинг'), ('sh_shohin', 'н. Шамсиддин Шоҳин'), ('jayhun', 'н. Ҷайҳун'), ('j_balkhi', 'н. Ҷалолиддини Балхӣ'), ('jomi', 'н. А.Ҷомӣ'), ('bahoriyon', 'н. Баҳориён'), ('nosiri_khusrav', 'н. Носири Хусрав'), ('rudaki', 'н. Рӯдакӣ'), ('varzob', 'н. Варзоб'), ('shahrinav', 'н. Шаҳринав'), ('fayzobod', 'н. Файзобод'), ('lakhsh', 'н. Лахш'), ('rasht', 'н. Рашт'), ('tojikobod', 'н. Тоҷикобод'), ('nurobod', 'н. Нуробод'), ('sangvor', 'н. Сангвор'), ('ayni', 'н. Айнӣ'), ('asht', 'н. Ашт'), ('b_gafurov', 'н. Бобоҷон Ғафуров'), ('devashtich', 'н. Деваштич'), ('zafarobod', 'н. Зафаробод'), ('k_mastchoh', 'н. Кӯҳистони Мастчоҳ'), ('mastchoh', 'н. Мастчоҳ'), ('spitamen', 'н. Спитамен'), ('j_rasulov', 'н. Ҷаббор Расулов'), ('istravshan', 'ш. Истаравшан'), ('isfara', 'ш. Исфара'), ('konibodom', 'ш. Конибодом'), ('panjakent', 'ш. Панҷакент'), ('guliston', 'ш. Гулистон'), ('bostan', 'ш. Бӯстон'), ('istiqlol', 'ш. Истиқлол'), ('darvoz', 'н. Дарвоз'), ('vanj', 'н. Ванҷ'), ('rushon', 'н. Рӯшон'), ('shughnon', 'н. Шугнон'), ('roshtqala', 'н. Роштқалъа'), ('ishkoshim', 'н. Ишкошим'), ('murghob', 'н. Мурғоб')], default='dushanbe', max_length=50, verbose_name='Шаҳр/Ноҳия'),
        ),
    ]
