# Generated by Django 5.2.14 on 2026-06-01 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_vip_cheque_alter_product_is_vip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_vip',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vip_cheque',
        ),
    ]
